#model parameters
model_type: "x_transformer_encoder"
model_task: "regression"
num_classes: 2  # Invalid for regression task
num_layers: 12
d_model: 512
nhead: 8
d_ff: 512
dropout_rate: 0.1
pooling: 'mean'

#training parameters
num_epochs: 10
seed_value: 41
batch_size: 512
num_workers: 2
learning_rate: 0.001
lr_patience: 3

#data parameters
data_directory: '/glade/u/home/mlsample/work/aptamer_transformer/data/sars-cov2-raw'
classification_threshold: 0.9
n_quantiles: 1000
round_weighting: True # Only valid if load_saved_data_set is False

#x_transformer parameters
num_tokens: 6
max_seq_len: 41

attn_flash: True
attn_num_mem_kv: 16
num_memory_tokens: 20
use_scalenorm: False
l2norm_embed: True
use_simple_rmsnorm: True
ff_glu: True
ff_swish: True
ff_no_bias: True
attn_talking_heads: False

#Convience parameters
debug: False
save_data_set: False
load_saved_data_set: True
load_last_checkpoint: False
